name: rUber
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  sizer: ^2.0.15
  shared_preferences: ^2.2.2
  dio: ^5.7.0
  connectivity_plus: ^5.0.2
  fl_chart: ^0.65.0
  fluttertoast: ^8.2.4
  google_fonts: ^6.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
